// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./components/dragbar/bar.vue')['default']
    Dragbar: typeof import('./components/dragbar/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tem: typeof import('./components/tem.vue')['default']
  }
}

export {}
